Formatting, along with field privacy and renaming Hatch to VelcroHatch.
TeamCautionRobotics/2019-FRC-robot pull request #16
Opened 2019-02-03 02:17 UTC by TaeSeanDo

2019-02-06 03:37 UTC, docprofsky requested changes
This is a very omnibus commit. Maybe also try to make pull requests smaller, with a narrower focus, and more atomic.

2019-02-06 03:37 UTC, docprofsky commented on .vscode/settings.json
> +"editor.renderWhitespace": "boundary"
This is out of scope for this PR, but eh :man_shrugging: .

2019-02-06 03:37 UTC, docprofsky commented on src/main/java/com/teamcautionrobotics/robot/Flashlight.java
> +}
This seems out of scope for this PR. Also, should there be an implementation for Flashlight?

2019-02-06 03:37 UTC, docprofsky commented on src/main/java/com/teamcautionrobotics/robot/Robot.java
> +    private final SendableChooser<String> m_chooser = new SendableChooser<>();
While we are doing the reformatting, these fields (lines 43 - 46) and all references to them (located in `autonomousInit` and `autonomousPeriodic`) can be deleted.

2019-02-06 03:37 UTC, docprofsky commented on src/main/java/com/teamcautionrobotics/robot/Robot.java
> +     */
This whole comment can go.

2019-02-06 03:37 UTC, docprofsky commented on src/main/java/com/teamcautionrobotics/robot/VelcroHatch.java
> +
Remove extra line
```suggestion
```

2019-02-06 03:37 UTC, docprofsky commented on src/main/java/com/teamcautionrobotics/robot/Robot.java
> +
Should this new line be here?

2019-02-06 03:37 UTC, docprofsky commented on src/main/java/com/teamcautionrobotics/robot/ExpanderHatch.java
> +
This new line probably does not belong here.
Also, surprise, a wild file appears.
```suggestion
```

2019-02-06 03:37 UTC, docprofsky commented on src/main/java/com/teamcautionrobotics/robot/ExpanderHatch.java
> +
A wild newline appears.

2019-02-07 01:06 UTC, docprofsky approved these changes

2019-02-07 03:28 UTC, Ben1492 approved these changes

2019-02-07 04:40 UTC, merged